### ISSUE TITLE
Passing parameter to NavigateAsync

### ISSUE THREAD

**Issue by Caerusoft** [sebcam/CrossSync#2]
Hi,

I am trying to use your navigation service, however I cannot work out how to call using a parameter.  Essentially I have the following code.  I would like to pass the object called "selected" as a parameter to the view model.  I'm sure it's really simple, but I cannot work out how to do it! 

        async void UpsertFoo(FooItem selected)
        {
            await navigationService.NavigateAsync<FooItemUpsertViewModel>();
        }

Any pointers would be greatly appreciated!

**Comment by sebcam** [comment]
Hi,
You should be able to do this :


```
public class FooItemUpsertViewModel : IViewModel<FooItem> // OR BaseViewModel<FootItem>
{
...
}
```

```
async void UpsertFoo(FooItem selected)
{ 
   await navigationService.NavigateAsync<FooItemUpsertViewModel>(selected);
}
```

Just be careful if you pass in an instance of an object because it is passed by ref, and you should not alter this object in your new page.
In the case you selected a record, and want to go to edit page, may be you should just pass the ID in the navigation service, and reload the object in your viewmodel.

**Comment by Caerusoft** [comment]
Thanks for your help...
